# `sheldon` configuration file
# ----------------------------

shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["source"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-interactive-cd]
github = "changyuheng/zsh-interactive-cd"

[plugins.zsh-256color]
github = 'chrissicool/zsh-256color'
use = ['zsh-256color.plugin.zsh']

[plugins.zshmarks]
github = 'jocelynmallon/zshmarks'

[plugins.kubectl-completion]
remote = "https://raw.githubusercontent.com/nnao45/zsh-kubectl-completion/master/_kubectl"
apply = ["fpath"]

[plugins.fzf-zsh-completions]
github = 'chitoku-k/fzf-zsh-completions'
use = ['fzf-zsh-completions.plugin.zsh']

[plugins.zeno]
github = 'yuki-yano/zeno.zsh'

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
